#!/bin/bash

echo "Cambiando direccion de librerias..."
export LD_LIBRARY_PATH="librerias/fmod/lowlevel/lib/x86_64/:librerias/fmod/studio/lib/x86_64/:librerias/irrlicht/lib/:librerias/reactphysics3d/lib:librerias/glew/lib:librerias/glad/lib:librerias/glfw/lib:librerias/assimp/lib:librerias/curl/lib:"
./Ejecutable
